---
title: "writing functions"
Author: "Marelle"
format: html
---

## Setup

```{r}
### For data wrangling and plotting
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
install.packages("purrr")
library(purrr) ### for iteration using map() family of functions

library(palmerpenguins) ### example data
```

## Function Basics 

```{r}

### Example code 
#my_function <- function(argument1, argument2) {
 # <code that performs some well defined task>
  #return(result)
#}
```

## Temp conversion example

```{r}
airtemps <- c(212, 30.3, 78, 32)
celsius1 <- (airtemps[1] - 32) * 5/9
celsius2 <- (airtemps[2] - 32) * 5/9
celsius3 <- (airtemps[3] - 33) * 5/9 #typo repeating this so lets put it into a function



convert_f_to_c <- function(fahr) {
  celsius <- (fahr - 32) * 5/9
  return(celsius)
}

 ### check single value:
celsius1a <- convert_f_to_c(airtemps[1])
celsius1a == celsius1

### calculate for whole vector:
celsius_vec <- convert_f_to_c(airtemps)
celsius_vec
```

## Setting argument defaults 

```{r}
##assume user is giving temp in F
convert_temp <- function(t, scale = 'f') {
  scale = tolower(substr(scale,1,1))
  if(!scale %in% c('c','f')) {
    stop('Scale must be either "c" or "f"!')
  }
    if(scale == "c") {
        result = t * 9/5 + 32
    } else {
        result  = (t - 32) * 5/9
    }
    return(round(result, 3))
}

convert_temp(t=airtemps, scale = 'celsius')
```

## Returning Values
```{r}
convert_f_to_c_k <- function(f) {
  c <- (f - 32) * 5/9
  k  <- c + 273.15
  out_df <- data.frame(fahr = f, celsius = c, kelvin = k)
  return(out_df)
}

temps_df <- convert_f_to_c_k(seq(-100, 100, 50))
temps_df
```

## Functions and Environments
```{r}
a <- 1       ### create object a in parent environment

add_one <- function(x) {
  x <- x + 1 ### increment argument by 1
  a <- a + 2 ### modify a in function environment
  b <- a + 3 ### create b in function environment
  return(x)  ### only x is returned back to parent
}

add_one(a)   ### give `a` as arg to the function; returns the value a + 1
```

## Functions for iterations


```{r}
#Simple
nums <- list(1, 3, 9, 49, 101, pi)
purrr::map_vec(.x = nums, .f = sqrt)
base::sapply(X = nums, FUN = sqrt)

#Complex
install.packages("broom")
library(palmerpenguins)
data(penguins)
spp_vec <- unique(penguins$species)

calc_bill_model <- function(spp, df) {
    spp_df <- df %>%
        filter(species == spp)
    bill_mdl <- lm(bill_length_mm ~ bill_depth_mm, data = spp_df)
    return(bill_mdl)
}
map_results <- purrr::map(.x = spp_vec, .f = calc_bill_model, df = penguins)
broom::tidy(map_results[[3]])
lapply_results <- base::lapply(X = spp_vec, FUN = calc_bill_model, df = penguins)
broom::tidy(lapply_results[[3]])
```

## Custom plots


```{r}
custom_theme <- function(base_size = 9) {
  theme(
    text             = element_text(family = "serif",
                                    color  = "slateblue4",
                                    size   = base_size),
    plot.title       = element_text(size   = rel(1.25),
                                    hjust  = 0.5,
                                    face   = "bold"),
    panel.background = element_rect(color = 'slateblue3',
                                    fill  = 'azure'),
    panel.grid.major = element_line(color    = "slateblue1",
                                    linewidth = 0.25),
    legend.position  = c(.9, .4),
    axis.ticks       = element_line(color = 'red')
  )
}

scatterplot <- function(df, point_size = 2, font_size = 9) {
  ggplot(data = df, mapping = aes(x = fahr, y = celsius, color = kelvin)) +
    geom_point(size = point_size) +
    scale_color_viridis_c() +
    custom_theme(font_size)
}

scatterplot(temps_df, point_size = 3, font_size = 16) +
  labs(title = 'Temperature Conversions')
```

## Documenting functions
```{r}
#' Convert temperature from Fahrenheit to Celsius
#'
#' @param fahr Numeric value or vector in degrees Fahrenheit
#'
#' @returns Numeric value or vector in degrees Celsius
#' @export
#'
#' @examples
#' convert_f_to_c(32)
#' convert_f_to_c(c(32, 212, 72))
convert_f_to_c <- function(fahr) {
  celsius <- (fahr - 32) * 5/9
  return(celsius)
}
```