---
title: "Data Visualization"
format: html
---

## Load packages

```{r}
### Data wrangling
library(readr)
library(here)      ### for robust relative file paths
library(dplyr)
library(tidyr)
library(forcats)   ### tools for working with factors (e.g., reordering)
library(janitor)   ### clean column names
library(DT)
library(leaflet)

### Visualization
library(ggplot2)

### Interactive output
library(plotly)
```


```{r}
# read in data from the data directory after manually downloading data 
delta_visits_raw <- read_csv(here("data/raw/Socioecological_monitoring_data.csv"))
```

```{r}
### Check out column names
colnames(delta_visits_raw)

### Peek at each column and class
glimpse(delta_visits_raw)

### From when to when
range(delta_visits_raw$Date)

### Which time of day?
unique(delta_visits_raw$Time_of_Day)
```

## Clean column names
```{r}
colnames(delta_visits_raw)[1:6]

delta_visits <- delta_visits_raw %>%
  janitor::clean_names()

colnames(delta_visits)[1:6]
```

## Reshape to tidy data
```{r}
visits_long <- delta_visits %>%
  tidyr::pivot_longer(
    cols = c(sm_boat, med_boat, lrg_boat, bank_angler, scientist, cars),
    names_to = "visitor_type",
    values_to = "quantity"
  ) %>%
  ### shorten the long name:
  dplyr::rename(restore_loc = eco_restore_approximate_location) %>%
  ### drop the notes column:
  dplyr::select(-notes)

glimpse(visits_long)
```

```{r}
daily_visits_loc <- visits_long %>%
    dplyr::group_by(restore_loc, date, visitor_type) %>% 
    dplyr::summarize(daily_visits = sum(quantity), .groups = 'drop')
    
glimpse(daily_visits_loc)
```

## GGPlot2 - make some plots

```{r}
 ggplot(data = daily_visits_loc,
       mapping = aes(x = restore_loc, y = daily_visits)) +
  geom_col() + 
  labs(title = 'Plot title')
```

```{r}
daily_visits_loc %>%
    filter(daily_visits < 30,
           visitor_type %in% c("sm_boat", "med_boat", "lrg_boat")) %>%
    ggplot(aes(x = visitor_type, y = daily_visits)) +
    geom_boxplot()
```


```{r}
ggplot(data = daily_visits_loc,
       aes(y = restore_loc, x = daily_visits, fill = visitor_type)) +
  geom_col() +
  labs(x = "Number of Visits",
       y = "Restoration Location",
       fill = "Visitor Type",
       title = "Total Visits to Delta Restoration Areas by Visitor Type",
       subtitle = "Sum of all visits July 2017 - March 2018") +
  scale_x_continuous(breaks = seq(0, 120, 20), expand = c(0, 0)) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    axis.ticks.y = element_blank()
  )
```


```{r}
facet_plot <- ggplot(data = daily_visits_loc,
       aes(x = visitor_type, y = daily_visits,
           fill = visitor_type)) +
    geom_col() +
    facet_wrap(~restore_loc,
               scales = "free_y",
               ncol   = 5,
               nrow   = 2) +
    scale_fill_viridis_d() +
    labs(x        = "Type of visitor",
         y        = "Number of Visits",
         title    = "Total Number of Visits to Delta Restoration Areas",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.x    = element_blank(),
          axis.text.x     = element_blank())

facet_plot
```


```{r}
ggplotly(facet_plot, tooltip = c('x', 'y'))
```

## Show an interactive table 

```{r}
DT::datatable(
  daily_visits_loc,
  caption  = "Daily visitor counts at Delta restoration sites",
  colnames = c("Location", "Date", "Visitor type", "Daily visits"),
  options  = list(pageLength = 10)
)
```

## Show an interactive map 

```{r}

restoration_sites <- delta_visits %>% 
    clean_names() %>% 
    distinct(restore_loc = eco_restore_approximate_location, 
           latitude, longitude) %>%
           drop_na(latitude, longitude)
        restoration_sites

leaflet(restoration_sites) %>%
    addTiles()%>%
    addMarkers(lng = ~longitude,
                lat = ~latitude)
```

