---
title: "American RST data cleaning"
format: html
Author: "Marelle"
---

# Set up 

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(readr)
library(here)
library(tidyverse)
library(lubridate)
library(janitor)
```

# Read in data 
```{r}
amer_catch <- read_csv(here("salmon/raw_data/amer_raw_catch_chinook.csv"))
amer_enviro <- read_csv(here("salmon/raw_data/amer_environmentals.csv"))
```


# Tidying enviro data 
```{r}
#changing date to YYYY-MM-DD

amer_enviro$Date <- format(as.Date(amer_enviro$Date, format = "%m/%d/%Y"), "%Y-%m-%d")

#adding column for calendar year and water year

library(lubridate)

amer_enviro_lub <- amer_enviro %>%
  mutate(
    Date = ymd(Date),  # converts character to Date
    calendar.year = year(Date),
    water.year = if_else(month(Date) >= 10,
                         year(Date) + 1,
                         year(Date))
  )

#remove decimal from year columns 

amer_enviro_lub <- amer_enviro_lub %>%
  mutate(water.year = as.integer(water.year))

amer_enviro_lub <- amer_enviro_lub %>%
  mutate(calendar.year = as.integer(calendar.year))

#updating column header names to be uniform (all lowercase, periods between words)

library(janitor)
amer_enviro_lub_clean <- amer_enviro_lub %>% clean_names(case = "snake") %>%
  rename_with(~ gsub("_", ".", .x))


table(month(amer_enviro_lub_clean$date, label = TRUE))

#exporting clean tidy data

write.csv(amer_enviro_lub_clean, "salmon/tidy_data/amer_environmentals_tidy.csv", row.names = FALSE)

```

# Tidying chinook catch data 

```{r}
amer_catch$Date <- format(as.Date(amer_catch$Date, format = "%m/%d/%Y"), "%Y-%m-%d")

#adding column for calendar year and water year

amer_catch_lub <- amer_catch %>%
  mutate(
    Date = ymd(Date),  # converts character to Date
    calendar.year = year(Date),
    water.year = if_else(month(Date) >= 10,
                         year(Date) + 1,
                         year(Date))
  )

#remove decimal from year columns 

amer_catch_lub <- amer_catch_lub %>%
  mutate(water.year = as.integer(water.year))

amer_catch_lub <- amer_catch_lub %>%
  mutate(calendar.year = as.integer(calendar.year))

#updating column header names to be uniform (all lowercase, periods between words)

amer_catch_lub_clean <- amer_catch_lub %>% clean_names(case = "snake") %>%
  rename_with(~ gsub("_", ".", .x))


table(month(amer_catch_lub_clean$date, label = TRUE))

#exporting clean tidy data

write.csv(amer_catch_lub_clean, "salmon/tidy_data/amer_catch_tidy.csv", row.names = FALSE)

```

# Join tidy enviro and catch data 

```{r}
amer_combined <- amer_catch_lub_clean %>%
  left_join(amer_enviro_lub_clean, by = c("date", "trap.visit.id", "sub.site.name"))

#check that left join worked correctly
#number of fish records should match exactly
nrow(amer_catch_lub_clean)      
nrow(amer_combined)    

write.csv(amer_combined, "salmon/tidy_data/amer_combined.csv", row.names = FALSE)

```
